config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'fights#new'

  resources :fighters
  resources :fights
  resources :rankings, only: [:index] 
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fight.rb
class Fight < ApplicationRecord
  validates :loser, presence: true
  validates :winner, presence: true
  validate :different_winner_and_loser

  belongs_to :loser, class_name: "Fighter"
  belongs_to :winner, class_name: "Fighter"

  def different_winner_and_loser
    errors.add(:loser, "can't be the same as winner") if loser == winner
  end

end

app/models/fighter.rb
class Fighter < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :lifepoints, presence: true, inclusion: { in: 90..110, message: "should range between 90 and 110" }
  validates :hitpoints, presence: true, inclusion: { in: 5..15, message: "should range between 5 and 15" }

  has_many :defeats, class_name: "Fight", foreign_key: "loser_id"
  has_many :victories, class_name: "Fight", foreign_key: "winner_id"
  has_one_attached :avatar

  def fights
    Fight.where(loser: self).or(Fight.where(winner: self))
  end

  def winrate
    if self.fights.count > 0
      "#{((self.victories.count.to_f / self.fights.count.to_f)*100).to_i}%"
    else
      0
    end
  end

  def attacks(fighter, weapon, shield)
    if self.lifepoints > 0
      recap = []
      recap << "#{self.name.capitalize} attacks #{fighter.name.capitalize}"
      damage_inflicted = self.hitpoints + (self.experience / 10) + weapon + rand(-5..5)
      recap << "Damage is #{damage_inflicted}"
      recap << fighter.gets_damage(damage_inflicted)
    end
  end

  def gets_damage(damage)
    self.lifepoints -= damage
    inflicted_damage_message = "#{self.name.capitalize} has #{self.lifepoints} lifepoints left"
  end

  def accessory_value(accessory)
    if accessory == "Gold"
      4
    elsif accessory == "Silver"
      3
    else
      2
    end
  end

end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  helper_method :avatar

  #Allows us to grab current_user profile pic in all cases (if there is no attached avatars, we display a default avatar)
  def avatar(avatar_holder)
      if avatar_holder.avatar.attached?
          avatar = avatar_holder.avatar
      else
          avatar = "https://arena-fighter.s3.eu-west-3.amazonaws.com/avatar.jpg"
      end
  end
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  def index
    @fighters = Fighter.all
  end

  def show
    @fighter = Fighter.find(params[:id])
  end

  def new
    @fighter = Fighter.new
  end

  def create
    @fighter = Fighter.new(fighter_params)
    @fighter.avatar.attach(fighter_params[:avatar])
      if @fighter.save
        flash[:success] = "Fighter created!"
        redirect_to fighter_path(@fighter)
      else
        flash[:error]
        render 'new'
      end
  end

  def edit
    @fighter = Fighter.find(params[:id])
  end

  def update
    @fighter = Fighter.find(params[:id])

    if @fighter.update(fighter_params)
      flash[:success] = "Update successful"
      redirect_to fighter_path(@fighter)
    else
      render 'edit'
    end
  end

  def destroy
    @fighter = Fighter.find(params[:id])

    if @fighter.destroy
      flash[:success] = "Fighter deleted"
      redirect_to fighters_path
    else
      render 'destroy'
    end
  end

  private
  def fighter_params
      params.require(:fighter).permit(:name, :lifepoints, :hitpoints, :experience, :avatar)
  end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  def index
    @fights = Fight.all
  end

  def new
    @fighters = Fighter.all
    @fight = Fight.new
    @accessories = ["Gold", "Silver", "Bronze"]
  end

  def create
    @fighters = Fighter.all
    @fight = Fight.new
    @accessories = ["Gold", "Silver", "Bronze"]
    cookies.delete :flash
    @fighter1 = Fighter.find(params[:fighter1])
    @fighter2 = Fighter.find(params[:fighter2])
      if @fighter1 == @fighter2
        flash[:error] = "Both fighters must be different"
        render 'new'
      else
        fight_sequence = FightSequence.new(
        @fighter1,
        @fighter1.accessory_value(params[:weapon1]),
        @fighter1.accessory_value(params[:shield1]),
        @fighter2,
        @fighter2.accessory_value(params[:weapon2]),
        @fighter2.accessory_value(params[:shield2])
        ).fight
        @fight = Fight.new(loser: fight_sequence[:loser], winner: fight_sequence[:winner])
          if @fight.save
            flash[:notice] = fight_sequence[:fight_recap]
            redirect_to root_path
          else
            render 'new'
          end
      end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true
class PagesController < ApplicationController
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def index
    @fighters = Fighter.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/fighters/edit.html.haml
%p
  = form_for(@fighter) do |f|
    = f.label 'Name'
    = f.text_field 'name', autofocus: true

    = f.label 'Lifepoints'
    = f.text_field 'lifepoints'

    = f.label 'Hitpoints'
    = f.text_field 'hitpoints'

    = submit_tag "Edit Fighter"

app/views/fighters/index.html.haml
%body{style: "background-color: #F3F3F3"}
  -2.times do
    %br/
  %h1.row.justify-content-center
    All Fighters
  %br/
  .row.justify-content-center
    .col-5{style: "background-color:white"}
      - @fighters.each do |fighter|
        .row.align-items-center
          = link_to fighter_path(fighter), class: "text-decoration-none", style: "color:black" do
            = image_tag url_for(avatar(fighter)), class: "avatar"
            %strong= "#{fighter.name.capitalize}"
            = ", Lifepoints: #{fighter.lifepoints}, Hitpoints: #{fighter.hitpoints}, Experience: #{fighter.experience}"
        %hr.m-2

app/views/fighters/new.html.haml
- @fighter.errors.each do |attr, msg|
  = attr
  = msg
  %br/

-2.times do
  %br/
%h1.row.justify-content-center
  New Fighter
%br/
.row.justify-content-center.text-center
  %p.form-signin.mt-3
    = form_for(@fighter) do |f|
      %label{class: "avatar", style: "background-color: grey; width:10em; height:10em; color:white"}
        %p{style:"padding-top:4em"}= "Add Photo"
        = f.file_field 'avatar', style: "display:none"
      .form-group.pt-3
        = f.text_field 'name', placeholder: "Name", autofocus: true
      .form-group
        = f.text_field 'lifepoints', placeholder: "Lifepoints (90 - 110)"
      .form-group
        = f.text_field 'hitpoints', placeholder: "Hitpoints (5 - 15)"

      = submit_tag "Create Fighter", class: "btn btn-primary"

app/views/fighters/show.html.haml
%body{style: "background-color: #F3F3F3"}
  -2.times do
    %br/
  %h1.row.justify-content-center
    = @fighter.name
  %br/

.row.justify-content-center
  = image_tag url_for(avatar(@fighter)), class: "avatar", style: "width:10em; height: 10em"
%br/
.row.justify-content-center.text-center
  %ul
    %li
      = "Lifepoints: #{@fighter.lifepoints}"
    %li
      = "Hitpoints: #{@fighter.hitpoints}"
    %li
      = "Experience: #{@fighter.experience}"
    %li
      = "Winrate: #{@fighter.winrate}"
%br/
.row.justify-content-center.text-center
  %p
    = link_to "Edit", edit_fighter_path(@fighter), class: "btn btn-primary"
    = link_to "Delete", fighter_path(@fighter), method: "delete", class: "btn btn-danger"

app/views/fights/index.html.haml
%body{style: "background-color: #F3F3F3"}
  -2.times do
    %br/
  %h1.row.justify-content-center
    Fight History
  %br/

.row.justify-content-center
  .col-5{style: "background-color:white"}
    %strong.row.align-items-center{style: "border-bottom: 1px solid grey"}
      .col-1
        = "#"
      .col{style: "border-left: 1px solid grey; border-right: 1px solid grey"}
        = "Winner"
      .col
        = "Loser"
    - @fights.each do |fight|
      .row.align-items-center
        .col-1
          = fight.id
        .col{style: "border-left: 1px solid grey; border-right: 1px solid grey"}
          = link_to fighter_path(fight.winner), class: "text-decoration-none", style: "color:black" do
            = image_tag url_for(avatar(fight.winner)), class: "avatar"
            %strong= "#{fight.winner.name.capitalize}"
        .col
          = link_to fighter_path(fight.loser), class: "text-decoration-none", style: "color:black" do
            = image_tag url_for(avatar(fight.loser)), class: "avatar"
            %strong= "#{fight.loser.name.capitalize}"
      %hr.m-0

app/views/fights/new.html.haml
-2.times do
  %br/
.row.justify-content-center
  %h1 Welcome to Arena Fighter
.row.justify-content-center
  %p Select your best fighters and make them fight!

-3.times do
  %br/

= form_for(@fight) do |f|
  .row.justify-content-center
    .col-3
      .row.justify-content-center
        = image_tag url_for(avatar(@fighters.first)), class: "avatar", style: "width:12em; height:12em"
      %br/
      .row.justify-content-center
        .col-3.text-center
          = f.label 'Fighter 1'
          %br/
          = select_tag :fighter1, options_from_collection_for_select(@fighters, "id", "name", @fighters.first.id), class: "btn btn-dark dropdown-toggle", style: "height:2em"
        .col-3.text-center
          = f.label 'Weapon 1'
          %br/
          = select_tag :weapon1, options_for_select(@accessories), class: "btn btn-outline-dark dropdown-toggle", style: "height:2em"
        .col-3.text-center
          = f.label 'Shield 1'
          %br/
          = select_tag :shield1, options_for_select(@accessories), class: "btn btn-outline-dark dropdown-toggle", style: "height:2em"
    .col-1
      .row.justify-content-center.pt-5
        = image_tag "vs.png", style: "width:5em"
      .row.justify-content-center.pt-5.mt-5
        = submit_tag "Fight!", class: "btn btn-lg btn-danger"
    .col-3
      .row.justify-content-center
        = image_tag url_for(avatar(@fighters.last)), class: "avatar", style: "width:12em; height:12em"
      %br/
      .row.justify-content-center
        .col-3.text-center
          = f.label 'Fighter 2'
          %br/
          = select_tag :fighter2, options_from_collection_for_select(@fighters, "id", "name", @fighters.last.id), class: "btn btn-dark dropdown-toggle", style: "height:2em"
        .col-3.text-center
          = f.label 'Weapon 2'
          %br/
          = select_tag :weapon2, options_for_select(@accessories), class: "btn btn-outline-dark dropdown-toggle", style: "height:2em"
        .col-3.text-center
          = f.label 'Shield 2'
          %br/
          = select_tag :shield2, options_for_select(@accessories), class: "btn btn-outline-dark dropdown-toggle", style: "height:2em"

.row.justify-content-center.text-center
  - if flash[:notice]
    - flash[:notice][0..-2].each do |index|
      = index
      %br/
.row.justify-content-center.text-center
  - if flash[:notice]
    %strong= flash[:notice][-1]

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .navbar-brand
    = link_to "ArenaFighter", root_path, style: "text-decoration: none; color: black"
  %ul.navbar-nav
    %li.nav-item.pr-3= link_to "Fighters", fighters_path
    %li.nav-item.pr-3= link_to "History", fights_path
    %li.nav-item.pr-3= link_to "Ranking", rankings_path
  .col.d-flex.flex-row-reverse
    = link_to "Add Fighter", new_fighter_path, class: "btn btn-primary"

app/views/layouts/application.html.haml
%html
  %head
    %meta{charset: 'utf-8'}/
    %title
      ArenaFighter
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  %body

    = render "layouts/header"
    = flash[:success]
    = flash[:error]
    = yield

app/views/rankings/index.html.haml
%body{style: "background-color: #F3F3F3"}
  -2.times do
    %br/
  %h1.row.justify-content-center
    Ranking
  %br/

.row.justify-content-center
  .col-5{style: "background-color:white"}
    %strong.row.align-items-center{style: "border-bottom: 1px solid grey"}
      .col-1
        = "#"
      .col{style: "border-left: 1px solid grey; border-right: 1px solid grey"}
        = "Fighter"
      .col-2
        = "Victories"
      .col-2{style: "border-left: 1px solid grey; border-right: 1px solid grey"}
        = "Defeats"
      .col-2
        = "Winrate"
    - i = 0
    - @fighters.sort_by { |obj| -obj.victories.count }.each do |fighter|
      - i += 1
      .row.align-items-center
        .col-1
          = i
        .col{style: "border-left: 1px solid grey; border-right: 1px solid grey"}
          = link_to fighter_path(fighter), class: "text-decoration-none", style: "color:black" do
            = image_tag url_for(avatar(fighter)), class: "avatar"
            %strong= "#{fighter.name.capitalize}"
        .col-2
          = fighter.victories.count
        .col-2{style: "border-left: 1px solid grey; border-right: 1px solid grey"}
          = fighter.defeats.count
        .col-2
          = fighter.winrate
      %hr.m-0